import "./globals.css";
import "primereact/resources/themes/lara-light-blue/theme.css";
import "primeicons/primeicons.css";
// import "primereact/resources/themes/tailwind-light/theme.css";

export const metadata = {
  title: "Sharemate",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  );
}
